utxostack/rgbpp-sdk

- packages/ckb/src/index.ts
- packages/ckb/src/queue/index.ts
- packages/ckb/src/types/index.ts
- packages/ckb/src/types/queue.ts
- packages/ckb/src/types/rgbpp.ts
- Add queue RPC APIs
- Add queue RPC request and response types
@Flouse @ahonn
> feat(rpbpp-sdk/ckb): Add queue rpc

- packages/btc/src/address.ts
- packages/btc/tests/shared/utils.ts
- Fix issue in the `decodeAddress()` method where `0` was mistakenly transformed to `false` 
(thanks @Dawn-githup for debugging)
> fix: transparent network type transformation

- packages/btc/README.md
- Remove `new BtcAssetsApi` usage in the btc lib readme
- Add `sendRgbppUtxos` usage in the btc lib readme
> docs(rgbpp-sdk/btc): sync sendRgbppUtxos updates in readme

- packages/ckb/src/rgbpp/btc-jump-ckb.ts
- packages/ckb/src/rgbpp/btc-time.ts
- packages/ckb/src/utils/ckb-tx.spec.ts
- packages/ckb/src/utils/ckb-tx.ts
- Add `isLockArgsSizeExceeded` function to check the lock script size
- When the size of `toLock` is too large,  an error will be thrown
- Delete the same SPV client cell
> refactor(rgbpp-sdk/ckb): Check lock size and remove the same client cell

- packages/ckb/src/rgbpp/btc-time.ts
- packages/ckb/src/types/rgbpp.ts
The JoyID  needs to know the current status of the BTC time cells to display the expected status on the UI for its users
- Add `isBtcTimeCellsSpent` function to tell the JoyID whether the BTC time cells have been spent
> feat(rgbpp-sdk/ckb): Check btc time cells status

- packages/ckb/package.json
- packages/ckb/src/utils/ckb-tx.spec.ts
- packages/ckb/src/utils/ckb-tx.ts
- pnpm-lock.yaml
- Add `feeRate` to the `calculateTransactionFee` function
- Update the default `feeRate` from 1100 to 1000
- Update the `calculateTransactionFee`  tests
https://github.com/ckb-cell/rgbpp-sdk/issues/44
> refactor(rgbpp-sdk/ckb): Add feeRate to calculateTransactionFee

- .changeset/lovely-rings-do.md
- packages/btc/README.md
- packages/btc/package.json
- packages/btc/src/error.ts
- packages/btc/src/query/mempool.ts
- packages/btc/src/query/source.ts
- packages/btc/src/transaction/build.ts
- packages/btc/tests/DataSource.test.ts
- pnpm-lock.yaml
- Add `DataSource.getRecommendedFeeRates` and `DataSource.getAverageFeeRate` APIs
- When the `feeRate` prop in TxBuilder is undefined, get a fee rate from `DataSource.getAverageFeeRate`
The `getRecommendedFeeRates` API returns a `FeesRecommended` object, which offers several levels of fee rates for users to choose from. The overall ranking on satoshi costing from high to low, or confirm time spent from fastest to slowest, is as follows:
```
fastestFee > halfHourFee > economyFee > hourFee > minimumFee > minimumFee
```
On the other hand, the `getAverageFeeRate` API returns the `halfHourFee`. This means that if the user leaves the `feeRate` empty while initializing a `TxBuilder`, it uses the `halfHourFee` as the default fee rate.
`getRecommendedFeeRates` and `getAverageFeeRate`:
```ts …
```
> feat(rgbpp-sdk/btc): add mempool.space api to provide default fee rate

- packages/service/README.md
- packages/service/src/error.ts
- packages/service/src/service/base.ts
- packages/service/src/service/service.ts
- packages/service/src/types/base.ts
- packages/service/src/types/rgbpp.ts
- packages/service/tests/Service.test.ts
- Allow some RGBPP APIs to return `undefined` instead of throwing 404
- Catch code/message from the response when status !== 200 (suggested by @ahonn)
- Redefine `RgbppTransactionState` from an enum to a simple type (suggested by @duanyytop)
- Fix type RgbppApiCkbTransactionHash.spv_client.index from `number` to `srting` (suggested by @duanyytop)
- Fix type RgbppApiSendCkbTransactionPayload to add an extra layer
> fix(rgbpp-sdk/service): fix error handling and type issues

- packages/service/src/service/service.ts
- packages/service/tests/Service.test.ts
- Disable 404 return types to complete the rollback in #60 
- Rewrite tests to catch error when expecting the APIs to return 404
> fix(rgbpp-sdk/service): 404 return types and tests

- examples/rgbpp/README.md
- examples/rgbpp/local/3-btc-transfer.ts
- examples/rgbpp/local/4-btc-jump-ckb.ts
- examples/rgbpp/queue/1-mint-xudt.ts
- examples/rgbpp/queue/2-ckb-jump-btc.ts
- examples/rgbpp/queue/3-btc-transfer.ts
- examples/rgbpp/queue/4-btc-jump-ckb.ts
- examples/rgbpp/tsconfig.json
- packages/ckb/src/rgbpp/ckb-jump-btc.ts
- packages/service/src/types/rgbpp.ts
- Add examples with queue service 
- Update the CKB Tx fee of the jumping transaction from CKB to BTC
- Add failedReason to the RGBPP state response
- Update examples readme
> feat(rgbpp-sdk/ckb): Add examples with queue service

- examples/rgbpp/README.md
- examples/rgbpp/local/2-ckb-jump-btc.ts
- examples/rgbpp/local/3-btc-transfer.ts
- examples/rgbpp/local/4-btc-jump-ckb.ts
- examples/rgbpp/local/5-spend-btc-time-cell.ts
- examples/rgbpp/local/transfer-btc.ts
- examples/rgbpp/queue/2-ckb-jump-btc.ts
- examples/rgbpp/queue/4-btc-jump-ckb.ts
- examples/rgbpp/queue/no-merge-outputs/3-btc-transfer.ts
- examples/rgbpp/tsconfig.json
- packages/ckb/README.md
- packages/ckb/example/paymaster.ts
- packages/ckb/src/rgbpp/btc-transfer.ts
- packages/ckb/src/rgbpp/ckb-jump-btc.ts
- packages/ckb/src/types/rgbpp.ts
- Add BTC transfer example without CKB tx outputs merged
- Update examples BTC_ASSETS_API_URL default value
- Add `noMergeOutputCells` to `genBtcTransferCkbVirtualTx` function to support CKB tx without outputs merged
- BTC TX: https://mempool.space/testnet/tx/c51644a8dd77677da2ee0c925ff8fb7f6a60fd7e46e4bec9e6bedb57c42f2761
- CKB TX: https://pudge.explorer.nervos.org/transaction/0x7c4ab94fd4714c8436ff62673a331f048394657908dde2da3944e1ff9816cdaa
> feat(rgbpp-sdk/ckb): Add BTC transfer example without CKB tx outputs merged

- .changeset/dirty-walls-beg.md
- packages/btc/README.md
- packages/btc/src/api/sendBtc.ts
- packages/btc/src/api/sendRgbppUtxos.ts
- packages/btc/src/api/sendUtxos.ts
- packages/btc/src/transaction/build.ts
- packages/btc/tests/Transaction.test.ts
1. Add BTC Builder APIs to provide more transaction construction info, e.g. `feeRate` and `fee`
- Added: `createSendBtcBuilder`, `createSendUtxosBuilder`, `createSendRgbppUtxosBuilder`
- Refactored with the Builder APIs: `sendBtc`, `sendUtxos`, `sendRgbppUtxos`
2. Update readme and add BTC Builder APIs types
> feat(rgbpp-sdk/btc): btc builder apis

- examples/rgbpp/local/batch/2-ckb-jump-btc.ts
- packages/ckb/src/rgbpp/ckb-jump-btc.ts
- packages/ckb/src/types/rgbpp.ts
- Add `genCkbBatchJumpBtcVirtualTx` to realize a batch jump
- Add batch example for RGB++ assets jumping from CKB to BTC
https://pudge.explorer.nervos.org/transaction/0xfd5a4d897ed231f5d3afd155e95e9f90c2e99c1e71fc55f16ecd66b99411315f
> feat(rgbpp-sdk/ckb): Realize batch jump of assets from CKB to BTC

- packages/btc/README.md
- packages/btc/src/api/sendBtc.ts
- packages/btc/src/api/sendRgbppUtxos.ts
- packages/btc/src/api/sendUtxos.ts
- packages/btc/src/error.ts
- packages/btc/src/query/source.ts
- packages/btc/src/transaction/build.ts
- packages/btc/tests/Transaction.test.ts
- packages/service/src/types/btc.ts
- packages/service/tests/Service.test.ts
- packages/service/vitest.config.mts
1. Support the "only_confirmed" param in the BtcAssetsApi.getUtxos() API (refer to [btc-assets-api#40](https://github.com/ckb-cell/btc-assets-api/pull/40) and [btc-assets-api#41](https://github.com/ckb-cell/btc-assets-api/pull/41))
2. Support the "onlyConfirmedUtxos" option in the BTC APIs (`sendBtc`, `sendUtxos`, `sendRgbppUtxos`, and the BTC Builder APIs), and also validate inputs to check if each UTXO is confirmed
This is a `boolean` option that tells the API to look for confirmed UTXOs when collecting inputs for construction and fee. If not enough confirmed UTXOs to construct the transaction, the API will throw an INSUFFICIENT_UTXO error.
```ts
sendBtc({
// ...
onlyConfirmedUtxos: true, // optional, default to false
});
```
- The name of  the "onlyConfirmedUtxos" option is inherited …
> feat(btc|service): add option to filter confirmed utxos and validate inputs

- packages/btc/src/transaction/build.ts
- packages/btc/tests/Transaction.test.ts
1. Fix when `sum(ins) > sum(outs) && change < fee`, the returned change is incorrect (found by @duanyytop)
2. Fix when `outs` has only an `OP_RETURN` output, and `ins` has no UTXOs specified, the collection is skipped
Previously when the sum of ins is greater than the sum of outs, the process goes in the returning phase. But when calculating the return amount with `extraSatoshiInInputs - fee`, the `fee` can actually be greater then the `extraSatoshiInInputs`, in that case, the returning amount is a negative number.
To address the issue, I changed the check statement:
- from: `if (sum(ins) - sum(outs) > 0) { return change } else { colelct satoshi }`
- to: `if (sum(ins) - sum(outs) - fee > 0) { return change } else { colelct satoshi }`
The logic change should prevent errors when there is …
> fix(rgbpp-sdk/btc): fee estimation/collection issues

- packages/service/README.md
- packages/service/src/service/service.ts
- packages/service/src/types/rgbpp.ts
- packages/service/tests/Service.test.ts
- Sync the `/rgbpp/v1/paymaster/info` api from [btc-assets-api/pull/13](https://github.com/ckb-cell/btc-assets-api/pull/13)
- Sync the `/rgbpp/v1/transaction/retry` api from [btc-assets-api/pull/21](https://github.com/ckb-cell/btc-assets-api/pull/21)
> feat(rgbpp-sdk/service): sync apis from btc-assets-api #13 and #21

- packages/ckb/src/rgbpp/btc-jump-ckb.ts
- packages/ckb/src/rgbpp/btc-transfer.ts
- packages/ckb/src/utils/rgbpp.spec.ts
- packages/ckb/src/utils/rgbpp.ts
- Update estimated CKB tx fee according to `inputGroup` size
It is recommended that JoyID upgrade `@rgbpp-sdk/ckb` to avoid potential transaction failure caused by insufficient CKB tx fee @yuche
> refactor(rgbpp-sdk/ckb): Update estimated ckb tx fee

- packages/ckb/src/error/index.ts
- packages/ckb/src/utils/rgbpp.spec.ts
- packages/ckb/src/utils/rgbpp.ts
- Limit inputs and outputs to length 255 for commitment
- Add error code for custom error classes
- Add invalid commitment test case
> feat(rgbpp-sdk/ckb): Limit inputs and outputs to length 255 for commitment

- packages/service/src/service/service.ts
- packages/service/src/types/rgbpp.ts
add the query parameter of `with_data` on `/rgbpp/v1/transaction/:btc_txid/job` to return txid and ckbVirtualResult.
https://btc-assets-api.testnet.mibao.pro/docs/static/index.html#/RGB%2B%2B/get_rgbpp_v1_transaction__btc_txid__job
'/rgbpp/v1/transaction/ccee39f38e5ad162c21a44bc6add20577811f13e35575fcb9103ef725a73c79d/job?with_data=true'
> feat: update getRgbppTransactionState to support withData param

- packages/btc/tests/Transaction.test.ts
> fix: add static fee rate in tests to prevent fluctuating fee rate failures

- packages/ckb/src/rgbpp/btc-jump-ckb.ts
- packages/ckb/src/rgbpp/btc-transfer.ts
- packages/ckb/src/utils/ckb-tx.spec.ts
- packages/ckb/src/utils/ckb-tx.ts
- Deduplicate rgbppLockArgsList for xUDT transfer on BTC and leap from BTC to CKB
- CKB transaction inputs will have duplicate cells if duplication is not removed.
> fix(rgbpp-sdk/ckb): Deduplicate rgbpp lock args list

- packages/btc/README.md
- packages/btc/src/query/source.ts
- packages/btc/src/transaction/build.ts
- packages/btc/tests/DataSource.test.ts
- Add `onlyNonRgbppUtxos` option in the DataSource.collectSatoshi() API, tests are also updated
- Set `onlyNonRgbppUtxos = true` by default in the TxBuilder when collecting UTXOs
Previously, if the value of a RGBPP UTXO is `>= 546`, it may be used to pay fee in a transaction. With the `onlyNonRgbppUtxos` option added, the SDK can filter out RGBPP UTXOs in the satoshi collection process, therefore preventing misuse of RGBPP UTXOs.
- Resolves #122
> feat(btc): add "onlyNonRgbppUtxos" option in DataSource/TxBuilder

- packages/btc/src/api/sendRgbppUtxos.ts
- Add "needPaymasterOutput" check to the sendRgbppUtxos() API, and the paymaster output should be added only when needed, previously the paymaster output was added to an RGBPP-related transaction without conditions
Currently, the logic of `needPaymasterOutput` is simple:
```ts
const needPaymasterOutput = CKB_VTX.inputs.length < CKB_VTX.outputs.length;
```
As you can see, we're comparing the length of inputs and outputs to see if the CKB virtual transaction needs a paymaster cell. It's a solid solution and can work without issues in most cases. However, in some rare cases, the information can be inaccurate.
For example, if the following conditions are met:
1. Transferring a single spore (the CKB_VTX has 1 input and 1 output)
2. The target spore itself should pay for the transaction fee, …
> fix(btc): only add paymaster output when needed in sendRgbppUtxos() API

- packages/btc/src/api/sendRgbppUtxos.ts
1. Rename API: `sendRgbppUtxosBuilder` -> `createSendRgbppUtxosBuilder`
2. Deprecate the `sendRgbppUtxosBuilder` API (will be removed in the future)
> refactor(btc): rename and deprecate the sendRgbppUtxosBuilder() API

- .changeset/config.json
- .github/workflows/release.yml
- package.json
- pnpm-lock.yaml
- Use `@changesets/changelog-github` changelog style (with a thank you message and the link to PR)
- Give pull-request read and write permissions to the changesets action in the release workflow
- Allow the release action to be triggered when commits are pushed to the main branch
Let changesets generate the bump:
1. Push commits (via PR) to the main branch, then the changesets action will automatically create or update a bump PR
2. The bump PR includes version changes of the packages and a changelog, which we can review and merge manually
3. Once the bump PR is merged, the changesets action will release the updated packages to NPM/GitHub
Or we can mange the bump manually:
1. Run `changeset version` in local and it will bump version and generate changelog for the packages
2. Push the …
> chore: enable main branch release

- .github/workflows/test.yaml
- package.json
- Disable btc/service tests in the `test.yaml` to prevent PRs from being blocked
> chore(ci): disable btc/service tests temporary

- .github/workflows/test.yaml
- examples/rgbpp/eslint.config.js
- examples/rgbpp/local/1-ckb-jump-btc.ts
- examples/rgbpp/local/2-btc-transfer.ts
- examples/rgbpp/local/3-btc-jump-ckb.ts
- examples/rgbpp/local/4-spend-btc-time-cell.ts
- examples/rgbpp/local/batch/1-ckb-jump-btc.ts
- examples/rgbpp/local/launch/0-rgbpp-token-info.ts
- examples/rgbpp/local/launch/1-prepare-launch.ts
- examples/rgbpp/local/launch/2-launch-rgbpp.ts
- examples/rgbpp/local/launch/3-distribute-rgbpp.ts
- examples/rgbpp/local/transfer-btc.ts
- examples/rgbpp/package.json
- examples/rgbpp/queue/1-ckb-jump-btc.ts
- examples/rgbpp/queue/2-btc-transfer.ts
- examples/rgbpp/queue/3-btc-jump-ckb.ts
- examples/rgbpp/queue/no-merge-outputs/2-btc-transfer.ts
- examples/rgbpp/spore/0-cluster-info.ts
- examples/rgbpp/spore/1-prepare-cluster.ts
- examples/rgbpp/spore/2-create-cluster.ts
- examples/rgbpp/spore/3-create-spores.ts
- examples/rgbpp/spore/4-transfer-spore.ts
- examples/rgbpp/spore/7-leap-spore-to-btc.ts
- examples/rgbpp/spore/queue/4-transfer-spore.ts
- examples/rgbpp/xudt/0-token-info.ts
- examples/rgbpp/xudt/1-issue-xudt.ts
- examples/rgbpp/xudt/2-transfer-xudt.ts
- pnpm-lock.yaml
- Use `typescript-eslint` to check and format examples code
- Add `lint:fix` to the Github Actions test CI
> refactor(examples): Add examples eslint

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- Fixed an issue where the snapshot workflow failed due to lacks of `GITHUB_TOKEN` (found by @ahonn)
> Error: Please create a GitHub personal access token at https://github.com/settings/tokens/new with `read:user` and `repo:status` permissions and add it as the GITHUB_TOKEN environment variable
- Added `workflow_dispatch` in the snapshot workflow to allow manually snapshot release
- Removed `feat/transfer-spore` as the trigger of the snapshot workflow
- Other minor text or indent fixes
- Here's a snapshot action that worked: https://github.com/ckb-cell/rgbpp-sdk/actions/runs/8875439965
> fix(ci): GITHUB_TOKEN permission in the actions

- packages/service/README.md
- packages/service/src/error.ts
- packages/service/src/service/base.ts
- packages/service/src/types/base.ts
- packages/service/tests/Utils.test.ts
- Add `context` in the error object of the service lib
- Add error handling recipe in service lib readme
- Resolves #95
You can now find context in the `BtcAssetsApiError` if the error was thrown from a request:
```ts
try { 
... 
} catch (e) {
if (e instanceof BtcAssetsApiError) {
console.log(e.context?.request);
console.log(e.context?.response);
}
}
```
This is the type of `e.context`:
```ts
interface BtcAssetsApiContext {
request: {
url: string;
body?: Record<string, any>;
params?: Record<string, any>;
};
response: {
status: number;
data?: Record<string, any> | string;
};
}
```
> feat(service): throw service error with context

- packages/btc/README.md
- packages/btc/src/query/source.ts
- packages/btc/src/transaction/build.ts
1. Add an `allowInsufficient` option (set to `true` by default) to the DataSource.collectSatoshi() API to allow the collection process to be completed when the balance of the target address is insufficient, instead of throwing the INSUFFICIENT_UTXO error
2. Fix the expected amount of error when collected satoshi and the balance of the target address are both insufficient for a change output to be generated in the transaction (reported by @Dawn-githup)
> fix(btc): error message when reporting INSUFFICIENT_UTXO

- README.md
- packages/service/README.md
You can get a testnet access token through the [/token/generate](https://btc-assets-api.testnet.mibao.pro/docs/static/index.html#/Token/post_token_generate) API directly.
The mainnet BtcAssetsApi is currently limited to verified apps only.
When your app development is ready on testnet, and requires a mainnet access token,
please email us at f@cell.studio to request a mainnet JWT token.
In the email, please provide the following information about your app:
- `name`: Your app name, e.g. "rgbpp-app"
- `domain`: Your app domain, e.g. "rgbpp.app" (without protocol prefix)
> docs: update README related to assets-api

- .changeset/large-nails-greet.md
- packages/ckb/src/collector/index.ts
- packages/ckb/src/rgbpp/launch.ts
- packages/ckb/src/types/collector.ts
- Collect all rgbpp inputs without isMax parameter
> refactor(rgbpp-sdk/ckb): Collect all rgbpp inputs without isMax

- .changeset/config.json
- .changeset/flat-starfishes-confess.md
- README.md
- packages/rgbpp/README.md
- packages/rgbpp/package.json
- packages/rgbpp/src/btc.ts
- packages/rgbpp/src/ckb.ts
- packages/rgbpp/src/index.ts
- packages/rgbpp/src/service.ts
- packages/rgbpp/tsconfig.build.json
- packages/rgbpp/tsconfig.json
- pnpm-lock.yaml
- Add rgbpp sub package to RGB++ SDK
- Export common functions and types from rgbpp root path
- Export functions and types of sub packages from sub paths
> feat(rgbpp-sdk): Add rgbpp sub package

- .changeset/slimy-rockets-watch.md
- packages/btc/src/transaction/build.ts
- Fix the message of INSUFFICIENT_UTXO when `collected < targetAmount` (@Dawn-githup)
> fix(btc): message of INSUFFICIENT_UTXO

- .changeset/silly-emus-raise.md
- packages/btc/src/address.ts
- packages/btc/src/query/source.ts
- packages/btc/src/utils.ts
- packages/service/src/error.ts
- packages/service/src/service/base.ts
- Replace all "void 0" to "undefined" in the btc/service lib (code style update suggested by @ahonn at https://github.com/ckb-cell/rgbpp-sdk/pull/149#discussion_r1584155981)
> style(btc/service): replace all "void 0" to "undefined"

- packages/btc/src/api/sendRgbppUtxos.ts
- packages/ckb/src/rgbpp/btc-jump-ckb.ts
- packages/ckb/src/rgbpp/btc-transfer.ts
- packages/ckb/src/utils/ckb-tx.spec.ts
- packages/ckb/src/utils/ckb-tx.ts
- packages/ckb/src/utils/rgbpp.spec.ts
- packages/ckb/src/utils/rgbpp.ts
- Add `isRgbppCapacitySufficientForChange` function to check whether the capacity of inputs is sufficient for outputs
- Return the rest of the capacity to sender when the RGB++ change cell is needed
- Determine whether a paymaster cell is needed based on whether the capacity of the inputs is sufficient for the outputs
- Add `checkCkbTxInputsCapacitySufficient` function for BTC package to determine whether a paymaster cell is needed
- Update paymaster cell logic with new function `checkCkbTxInputsCapacitySufficient`
> fix(ckb/btc): Check rgbpp capacity for change and paymaster cell

- .changeset/stupid-donuts-grin.md
- packages/ckb/README.md
- packages/ckb/src/spore/spore.ts
- packages/ckb/src/types/spore.ts
- Add `buildAppendingIssuerCellToSporesCreateTx` function to build ckb raw tx to be signed for spores creation
- The Dapp can use this function to build ckb raw tx and let the JoyID wallet or other wallets to sign the tx
> feat(rgbpp-sdk/ckb): Build ckb raw tx for spore creation

- packages/service/src/service/base.ts
- packages/service/vitest.config.mts
- Refactor service request-related code to improve readability (suggested by @duanyytop)
> The change doesn't include logic changes, therefore no changeset was added
- https://github.com/ckb-cell/rgbpp-sdk/pull/165#discussion_r1597339921
- https://github.com/ckb-cell/rgbpp-sdk/pull/165#discussion_r1597339756
> refactor(service): minor readability improvements

- .changeset/changelog-format.cjs
- .changeset/config.json
- package.json
- pnpm-lock.yaml
- Update changelog format to remove the thank you message, and simplify the change line info
- Compare with the `origin/main` branch instead of `main` when running changesets
```
- [#{pull_request_id}]: {titleLine} ({users})\n{afterLines}
- [`{commit_hash_if_no_pull_request_id}`]: {titleLine} ({users})\n{afterLines}
- Updated dependencies [{commits.join(', ')}]
- {packageName1}@{version}
- {packageName2}@{version}
```
- [#180](https://github.com/ckb-cell/rgbpp-sdk/pull/180): Update changelog format ([@ShookLyngs](https://github.com/ShookLyngs))
- [`f4776ea`](https://github.com/ckb-cell/rgbpp-sdk/commit/f4776ea4796b0070cbcaa9f036d3663aabc0bf0b): Update changelog format ([@ShookLyngs](https://github.com/ShookLyngs))
- Updated dependencies …
> chore(ci): update changelog format

- .changeset/changelog-format.cjs
- Fix an issue in the `.changeset/changelog-format.cjs` file where the `commits` variable was not awaited, it was expected to be an Array instead of a Promise (source: https://github.com/ckb-cell/rgbpp-sdk/actions/runs/9171211422/job/25215054139)
> fix(changeset): missing await in the changelog format file

- packages/ckb/src/spore/spore.ts
- Update RGB++ inputs length of Spore creation TX to avoid witnesses error
> fix(rgbpp-sdk/ckb): Update RGB++ inputs length of Spore creation TX

- examples/rgbpp/spore/launch/2-create-cluster.ts
- examples/rgbpp/spore/launch/3-create-spores.ts
- Add more annotations and logs for spore examples
- Update new cluster RGB++ lock args for each spore creation TX
> docs(example): Add more annotations and logs for spore examples

- .github/workflows/snapshot.yml
- Fix [#163](https://github.com/ckb-cell/rgbpp-sdk/issues/163) by ensuring a temp changeset is always added before the `changeset version` command is executed
- Fix snapshot versioning by reverting code, should not run version command in the changesets/action
- Resolves #163
When releasing snapshots, we expect each package to be versioned as `0.0.0-snap-{timestamp}`, and things should work as expected if the `.changeset` folder contains at least one changeset. If the condition has not been met, the `changeset version` command will be skipped, which causes the versions of the packages and the changelog file remain the same as before.
An example of skipping (which causes the [#163](https://github.com/ckb-cell/rgbpp-sdk/issues/163) issue):
```
% changeset version --snapshot snap
🦋  warn No …
```
> chore(ci): fix snapshot versioning

- .changeset/afraid-pianos-do.md
- packages/btc/README.md
- packages/btc/src/query/cache.ts
- packages/btc/src/query/source.ts
- packages/btc/src/transaction/build.ts
- packages/service/README.md
- Support query data caching internally in TxBuilder/DataSource, preventing query from the service too often
- Add type changes in the #181 to the service readme
Previously, when collecting inputs for paying fees, the `BtcAssetsApi.getBtcUtxos()` API and the `BtcAssetsApi.getRgbppAssetsByBtcUtxo()` API were queried multiple times. In this PR, a DataCache is added to prevent querying the same API with the same params too often.
Reference: https://github.com/ckb-cell/rgbpp-sdk/issues/173#issuecomment-2112523137
> feat(btc|service): support internal query data caching in TxBuilder.payFee()

- examples/rgbpp/shared/utils.ts
- examples/rgbpp/spore/4-transfer-spore.ts
- examples/rgbpp/spore/5-leap-spore-to-ckb.ts
- examples/rgbpp/spore/launch/2-create-cluster.ts
- examples/rgbpp/spore/launch/3-create-spores.ts
- examples/rgbpp/spore/local/4-transfer-spore.ts
- examples/rgbpp/spore/local/5-leap-spore-to-ckb.ts
- examples/rgbpp/xudt/2-btc-transfer.ts
- examples/rgbpp/xudt/3-btc-leap-ckb.ts
- examples/rgbpp/xudt/launch/2-launch-rgbpp.ts
- examples/rgbpp/xudt/launch/3-distribute-rgbpp.ts
- examples/rgbpp/xudt/local/2-btc-transfer.ts
- examples/rgbpp/xudt/local/3-btc-leap-ckb.ts
- Logging Implementation: Added functionality to save ckbVirtualTxResult into a log file in examples/rgbpp/*.
- Comments Addition: Included comments within the codebase to remind developers to adhere to the suggestion of saving ckbVirtualTxResult before finalizing isomorphic transactions.
> refactor(examples): Save ckbVirtualTxResult locally

- .changeset/afraid-pianos-do.md
- .changeset/clean-chairs-nail.md
- .changeset/fast-mice-smash.md
- .changeset/flat-starfishes-confess.md
- .changeset/large-nails-greet.md
- .changeset/rude-feet-love.md
- .changeset/selfish-lions-trade.md
- .changeset/silly-emus-raise.md
- .changeset/slimy-eggs-mix.md
- .changeset/slimy-rockets-watch.md
- .changeset/stupid-donuts-grin.md
- .changeset/sweet-jeans-check.md
- .changeset/young-students-own.md
- packages/btc/CHANGELOG.md
- packages/btc/package.json
- packages/ckb/CHANGELOG.md
- packages/ckb/package.json
- packages/rgbpp/CHANGELOG.md
- packages/rgbpp/package.json
- packages/service/CHANGELOG.md
- packages/service/package.json
- [#157](https://github.com/ckb-cell/rgbpp-sdk/pull/157): Add rgbpp sub package ([@duanyytop](https://github.com/duanyytop))
- [#177](https://github.com/ckb-cell/rgbpp-sdk/pull/177): Fix the export of NetworkType/AddressType in the rgbpp lib ([@ShookLyngs](https://github.com/ShookLyngs))
- Updated dependencies [[`8a8e11b`](https://github.com/ckb-cell/rgbpp-sdk/commit/8a8e11bdca4d3fb8b8d20c771e116bb1684bb1c6), [`5e0e817`](https://github.com/ckb-cell/rgbpp-sdk/commit/5e0e8175a4c195e6491a37abedc755728c91cbed), [`a9b9796`](https://github.com/ckb-cell/rgbpp-sdk/commit/a9b9796f5ef8d27a9ad94d09a832bb9a7fe56c8e), [`9f9daa9`](https://github.com/ckb-cell/rgbpp-sdk/commit/9f9daa91486ca0cc1015713bd2648aa606da8717), [`299b404`](https://github.com/ckb-cell/rgbpp-sdk/commit/299b404217036feab409956d8888bf …
> Bump RGB++ SDK to v0.2.0

- .changeset/warm-tomatoes-worry.md
- examples/rgbpp/spore/4-transfer-spore.ts
- examples/rgbpp/spore/5-leap-spore-to-ckb.ts
- examples/rgbpp/spore/launch/2-create-cluster.ts
- examples/rgbpp/spore/launch/3-create-spores.ts
- examples/rgbpp/spore/local/4-transfer-spore.ts
- examples/rgbpp/spore/local/5-leap-spore-to-ckb.ts
- examples/rgbpp/tsconfig.json
- examples/rgbpp/xudt/launch/2-launch-rgbpp.ts
- examples/rgbpp/xudt/launch/3-distribute-rgbpp.ts
- packages/btc/src/api/sendRgbppUtxos.ts
- Add a `needPaymaster?: boolean` option to the `sendRgbppUtxos()` API, which can decide whether the paymaster output is required in a BTC_TX, if the value is undefined, everything should behave exactly as before:
```ts
function isNeedPaymasterOutput() {
if (needPaymaster !== undefined) {
// new option steps in when it's not undefined
return needPaymaster;
} else {
// the original check statement, if the value is undefined
return ckbVirtualTxInputsCapacity >= ckbVirtualTxOutputsCapacity;
}
}  
```
- Specify `needPaymaster: needPaymasterCell` manually in all spore exmaples, and in xudt launch examples
- Fix the `include` field in the `tsconfig.json` of the examples
> feat(btc|examples): add needPaymaster option in the sendRgbppUtxos() API

- .changeset/smart-pigs-compete.md
- packages/btc/package.json
- packages/btc/src/api/sendRgbppUtxos.ts
- packages/btc/src/transaction/build.ts
- packages/btc/src/utils.ts
- pnpm-lock.yaml
- Add `p-limit` and batch queries in the sendRgbppUtxos() and TxBuilder.validateInputs() to improve transaction construction time, when querying a group of individual requests, batch up to `10` requests each time
> feat(btc): batch queries to improve transaction build time

- packages/service/tests/Service.test.ts
- Skip dust_satoshi check in service tests temporary due to the /balance API changes in https://github.com/ckb-cell/btc-assets-api/pull/154
> The change is tiny, no changeset needed
One suggestion is that the requests in the unit tests should be mocked, so the changes to the btc-assets-api won't affect the tests of the rgbpp-sdk, nor will the rgbpp-sdk be affected by the networking conditions or otherwise. However, when developers wish to check the status of the service via the tests, an on-off switch option may also be required.
> test(service): skip dust_satoshi check in tests

- examples/xudt-on-ckb/1-issue-xudt.ts
- examples/xudt-on-ckb/2-transfer-xudt.ts
- packages/ckb/src/collector/index.ts
- packages/ckb/src/rgbpp/btc-jump-ckb.ts
- packages/ckb/src/rgbpp/btc-time.ts
- packages/ckb/src/rgbpp/btc-transfer.ts
- packages/ckb/src/rgbpp/ckb-jump-btc.ts
- packages/ckb/src/rgbpp/launch.ts
- packages/ckb/src/spore/cluster.ts
- packages/ckb/src/spore/leap.ts
- packages/ckb/src/spore/spore.ts
- packages/ckb/src/utils/cell-dep.spec.ts
- packages/ckb/src/utils/cell-dep.ts
- packages/ckb/src/utils/index.ts
Although [Lumos](https://github.com/ckb-js/lumos/pull/687) provides a function `refreshTypeIdCellDeps` to refresh the cell deps of a upgraded TypeID script, it requires the dApp developers themselves to handle it manually.
**But usually a dApp developer doesn't know when a TypeID script is updated.**
This PR introduces a mechanism to automatically get the TypeID scripts' latest cell deps, trying to make things easier.
- Add `fetchTypeIdCellDeps` function to fetch `cellDeps` from the GitHub JSON file
- Use `cellDepsSelected` parameter to select the `cellDeps` which are needed
- Use dynamic fetching `cellDeps` for all the RGB++ transactions
- If `fetchCellDepsJson` fails due to a network error, the [constants](https://github.com/ckb-cell/rgbpp-sdk/blob/develop/packages/ckb/src/constants/inde …
> feat(ckb|example): Dynamic fetching cell deps deployed by TypeID

- examples/xudt-on-ckb/package.json
- pnpm-lock.yaml
- Use `"rgbpp": "workspace:*"` in the `xudt-on-ckb` to fix action error in https://github.com/ckb-cell/rgbpp-sdk/actions/runs/9342746967/job/25711314942?pr=208#step:9:21
> fix: use rgbpp@worksapce:* to prevent unmatched version issues

- .changeset/serious-actors-explode.md
- packages/ckb/src/collector/index.ts
- Resolves https://github.com/ckb-cell/rgbpp-sdk/issues/211
ref: https://blog.cryptape.com/enhance-sudts-programmability-with-xudt#heading-xudt-cell
```yml
XUDT cell
On top of sUDT, xUDT extends a cell as follows:
data:
<amount: uint128> <xudt data>
```
> fix(ckb): load the first 16 bytes of the XUDT cell data

- examples/rgbpp/xudt/1-ckb-leap-btc.ts
- Fixed issue where ckb-leap-btc did not read environment variables correctly.
> fix(examples): ckb-leap-btc not reading env variables

- .changeset/tender-hornets-agree.md
- packages/btc/src/query/cache.ts
- packages/btc/src/query/source.ts
- packages/btc/tests/DataSource.test.ts
- packages/service/README.md
- packages/service/src/types/btc.ts
- packages/service/tests/Service.test.ts
- Adapt [btc-assets-api#154](https://github.com/ckb-cell/btc-assets-api/pull/154), adding new props and return values to the /balance and /unspent APIs
- Add `available_satoshi` and `total_satoshi` to the BtcAssetsApi.getBtcBalance() API
- Add `only_non_rgbpp_utxos` to the props of the BtcAssetsApi.getBtcUtxos() API
- Remove `service.getRgbppAssetsByBtcUtxo()` lines from the DataCollector.collectSatoshi()
- Remove `hasRgbppAssets` related variables/function from the DataCache
- Resolves #173 
No need to validate whether each UTXO is an RGBPP asset, the construction time is further optimized. Previously, if an address had 1000+ tiny UTXOs, it would take 40+ minutes to construct a transaction. After the PR, it should only take 10+ seconds. Therefore, the slow construction issue is …
> feat(service|btc): adapt btc-assets-api#154

- examples/rgbpp/package.json
- examples/xudt-on-ckb/package.json
- pnpm-lock.yaml
- Update the rgbpp-sdk version in the examples to v0.3.0.
> chore(examples): update rgbpp-sdk to v0.3.0

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/test.yaml
- Remove the "--no-git-tag" in the snapshot release workflow, allowing the changesets/action to work as expected
- Update comment style when new package versions have been released (send table to pull/issue comment)
> chore: update comment style and remove no-git-tag option in the snapshot.yaml

- .github/workflows/integration-test.yaml
- [chore(CI): Run integration-tests every day](https://github.com/ckb-cell/rgbpp-sdk/pull/221/commits/fec2b4b4626419a9cdd164672de7591fe5c958dc)
- [chore: only one integration-tests runs at a time](https://github.com/ckb-cell/rgbpp-sdk/pull/221/commits/4cd077b884bc43672a00512006c7960145c65fe6) since only one group of keys is used
> chore(CI): Run integration-tests every day

- examples/rgbpp/.env.example
- examples/rgbpp/README.md
- examples/rgbpp/env.ts
- examples/rgbpp/shared/btc-account.ts
- examples/rgbpp/spore/4-transfer-spore.ts
- examples/rgbpp/spore/5-leap-spore-to-ckb.ts
- examples/rgbpp/spore/launch/2-create-cluster.ts
- examples/rgbpp/spore/launch/3-create-spores.ts
- examples/rgbpp/spore/local/4-transfer-spore.ts
- examples/rgbpp/spore/local/5-leap-spore-to-ckb.ts
- examples/rgbpp/xudt/2-btc-transfer.ts
- examples/rgbpp/xudt/3-btc-leap-ckb.ts
- examples/rgbpp/xudt/launch/2-launch-rgbpp.ts
- examples/rgbpp/xudt/launch/3-distribute-rgbpp.ts
- examples/rgbpp/xudt/local/2-btc-transfer.ts
- examples/rgbpp/xudt/local/3-btc-leap-ckb.ts
- Add `BtcAccount` in the examplex/rgbpp to support both P2WPKH and P2TR
- Fill `BtcAccount.from` and `BtcAccount.fromPubkey` when constructing transactions
- Remove `btcAddress` and `btcKeyPair` relevant usage in the examples
- Sign PSBT with BtcAccount via the `signPsbt()` API
- Resovles #207
> feat(examples): support P2TR in examples/rgbpp

- .changeset/silly-rules-collect.md
- packages/service/src/service/service.ts
- packages/service/src/types/rgbpp.ts
- packages/service/tests/Service.test.ts
- Add BtcAssetsApi.getRgbppApiBalanceByAddress() API for querying RGBPP XUDT balances by a BTC address (this PR introduces the `/rgbpp/v1/address/:address/balance` API, which is supported by [btc-assets-api#146](https://github.com/ckb-cell/btc-assets-api/pull/146), [btc-assets-api#155](https://github.com/ckb-cell/btc-assets-api/pull/155) and other related PRs)
> feat(service): support BtcAssetsApi.getRgbppApiBalanceByAddress()

- .changeset/great-baboons-smash.md
- examples/rgbpp/xudt/2-btc-transfer.ts
- examples/rgbpp/xudt/local/2-btc-transfer.ts
- packages/rgbpp/README.md
- packages/rgbpp/package.json
- packages/rgbpp/src/index.ts
- packages/rgbpp/src/rgbpp/types.ts
- packages/rgbpp/src/rgbpp/xudt.ts
- pnpm-lock.yaml
- Export `buildRgbppTransferTx` from rgbpp package to generate CKB virtual TX and BTC tx to be signed
- Update L1 transfer example with the function `buildRgbppTransferTx`
```TypeScript
const buildRgbppTransferTx = async ({
ckb: {
collector,
xudtTypeArgs,
rgbppLockArgsList,
transferAmount,
ckbFeeRate,
},
btc: {
fromBtcAddress,
toBtcAddress,
btcDataSource,
fromPubkey,
feeRate
},
isMainnet,
}: RgbppTransferTxParams): Promise<RgbppTransferTxResult>
```
The `collector` and `btcDataSource` will be constructed in the `rgbpp-sdk-service` with some necessary variables from the environment.  The necessary request and response for the L1 transfer in the `rgbpp-sdk-service` are as follows: 
```TypeScript
interface RgbppTransferReq {
// The transferred RGB++ xUDT type script args
xudtTypeArgs: …
```
> feat(ckb|example): Export `buildRgbppTransferTx` from rgbpp package and update L1 transfer example

- examples/xudt-on-ckb/2-transfer-xudt.ts
- Fix the inputs capacity collecting error which causes the outputs capacity is larger than the inputs capacity
- Calculate the capacity for each output by using `calculateUdtCellCapacity` function instead of a fixed value to make sure the output capacity is correct
> fix(examples): Update inputs capacity for the xUDT transfer example

- .github/workflows/integration-test.yaml
- .github/workflows/test.yaml
- tests/rgbpp/env.ts
- tests/rgbpp/shared/prepare-utxo.ts
- tests/rgbpp/spore/4-transfer-spore.ts
- tests/rgbpp/spore/5-leap-spore-to-ckb.ts
- tests/rgbpp/spore/launch/1-prepare-cluster.ts
- tests/rgbpp/spore/launch/2-create-cluster.ts
- tests/rgbpp/spore/launch/3-create-spores.ts
- tests/rgbpp/xudt/1-ckb-leap-btc.ts
- tests/rgbpp/xudt/2-btc-transfer.ts
- tests/rgbpp/xudt/3-btc-leap-ckb.ts
1. Integrated testing switched from testnet3 to signet.
2. Refactored tests/rgbpp/xudt/* using buildRgbppTransferTx from the rgbpp package.
> refactor(tests): Refactor integration test cases

- .changeset/orange-mice-trade.md
- packages/btc/README.md
- packages/btc/src/address.ts
- packages/btc/src/api/sendRbf.ts
- packages/btc/src/api/sendRgbppUtxos.ts
- packages/btc/src/api/sendUtxos.ts
- packages/btc/src/transaction/build.ts
- packages/btc/src/transaction/fee.ts
- packages/btc/src/transaction/utxo.ts
- packages/btc/tests/Transaction.test.ts
- packages/btc/tests/shared/utils.ts
- Support including multi-origin UTXOs (P2TR/P2WPKH) as inputs in the same BTC transaction
- Support the `pubkeyMap` option in the sendUtxos(), sendRgbppUtxos() and sendRbf() API
- Rename the option `inputsPubkey` to `pubkeyMap` in the sendRbf() API (any better advice?)
- Delete the `onlyProvableUtxos` option from the sendRgbppUtxos() API as it's no longer needed
- Resolves #141
> feat(btc): support including multi-origin UTXOs

- packages/btc/README.md
- Remove deleted prop `onlyProvableUtxos` from the btc lib README
ref: https://github.com/ckb-cell/rgbpp-sdk/pull/228#pullrequestreview-2125739597
> docs(btc): remove deleted prop `onlyProvableUtxos` from the README

- .changeset/great-baboons-smash.md
- .changeset/orange-mice-trade.md
- .changeset/silly-rules-collect.md
- .changeset/spicy-cups-cheat.md
- .changeset/wise-years-swim.md
- packages/btc/CHANGELOG.md
- packages/btc/package.json
- packages/ckb/CHANGELOG.md
- packages/ckb/package.json
- packages/rgbpp/CHANGELOG.md
- packages/rgbpp/package.json
- packages/service/CHANGELOG.md
- packages/service/package.json
- [#228](https://github.com/ckb-cell/rgbpp-sdk/pull/228): Support including multi-origin UTXOs in the same transaction ([@ShookLyngs](https://github.com/ShookLyngs))
- Add `pubkeyMap` option in the sendUtxos(), sendRgbppUtxos() and sendRbf() API
- Rename `inputsPubkey` option to `pubkeyMap` in the sendRbf() API
- Delete `onlyProvableUtxos` option from the sendRgbppUtxos() API
- [#150](https://github.com/ckb-cell/rgbpp-sdk/pull/150): Support Full-RBF feature with the sendRbf() and createSendRbfBuilder() API ([@ShookLyngs](https://github.com/ShookLyngs))
- Add `excludeUtxos`, `skipInputsValidation` options in the `sendUtxos()` API to support the RBF feature
- Add `onlyProvableUtxos` option in the `sendRgbppUtxos()` API for future update supports
- Add `changeIndex` in the return type of the …
> Bump RGB++ SDK to v0.4.0

- .changeset/clean-snails-admire.md
- packages/service/src/service/service.ts
- packages/service/src/types/rgbpp.ts
- packages/service/tests/Service.test.ts
- pnpm-lock.yaml
- Add "type_script" in the return type of `/rgbpp/v1/address/{btc_address}/balance` API, and add "typeHash" in the return type of rgbpp assets-related APIs, adapting changes in [btc-assets-api#184](https://github.com/ckb-cell/btc-assets-api/pull/184) and [btc-assets-api#186](https://github.com/ckb-cell/btc-assets-api/pull/186)
- Update `pnpm-lock.yaml` file to the latest
> feat(service): adapt btc-assets-api#184 and #186

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- Fix comment format in `release` and `snapshot` workflows (reported by @duanyytop)
Previously, the comment on the commit that triggers the release/snapshot workflow was not formatted correctly, causing it to show only the first line of the table. Here's an example: https://github.com/ckb-cell/rgbpp-sdk/commit/53fc8eec4fb15974f4734de3913e528f4b1d0efc#commitcomment-143869323
The table should be fixed to:
| Name | Version |
| --- | --- |
| @rgbpp-sdk/btc | `0.0.0-snap-20240705090030` |
| @rgbpp-sdk/ckb | `0.0.0-snap-20240705090030` |
| rgbpp | `0.0.0-snap-20240705090030` |
| @rgbpp-sdk/service | `0.0.0-snap-20240705090030` |
> fix(ci): comment format in release/snapshot workflows

- .changeset/sweet-singers-hang.md
- examples/rgbpp/spore/launch/3-create-spores.ts
- packages/ckb/README.md
- packages/ckb/src/spore/leap.ts
- packages/ckb/src/spore/spore.ts
- packages/ckb/src/types/spore.ts
- packages/ckb/src/utils/ckb-tx.spec.ts
- packages/ckb/src/utils/ckb-tx.ts
- Allow RGB++ spore cell not to reserve more CKB for `btc_time_lock` cell when creating spores
- When the spore cell capacity is not sufficient for leaping from BTC to CKB, a paymaster cell is needed
- Add `calculateCellOccupiedCapacity` and `isSporeCapacitySufficient` util methods and related tests
> feat(rgpp-sdk/ckb): Allow RGB++ spore cell not to reserve CKB

- .changeset/sweet-singers-hang.md
- examples/rgbpp/spore/launch/2-create-cluster.ts
- examples/rgbpp/spore/launch/3-create-spores.ts
- packages/ckb/README.md
- packages/ckb/src/spore/leap.ts
- packages/ckb/src/spore/spore.ts
- packages/ckb/src/types/spore.ts
- packages/ckb/src/utils/ckb-tx.spec.ts
- packages/ckb/src/utils/ckb-tx.ts
- Disable minimal RGB++ spore-occupied capacity to avoid leaping from BTC to CKB fail
> feat(ckb | example): Disable minimal rgbpp spore capacity

- examples/rgbpp/xudt/4-unlock-btc-time-cell.ts
- examples/xudt-on-ckb/3-generate-btc-time-cell.ts
- Add generating BTC time cell example with custom `BTC tx id`, `after` and `toLockScript`
> feat(example): Add generating btc time cell example

- .changeset/shy-tables-turn.md
- packages/btc/src/api/sendRgbppUtxos.ts
- Batch fetching CKB RGB++ live cells to construct BTC tx
- Remove useless fields for RGB++ lock args list
> refactor(btc): Batch fetching CKB RGB++ live cells

- .changeset/sharp-wasps-punch.md
- packages/ckb/src/utils/ckb-tx.spec.ts
- packages/ckb/src/utils/ckb-tx.ts
- packages/ckb/src/utils/rgbpp.ts
- Considering the BTC time cell capacity cannot be used for transaction fees, removing 1CKB from BTC time cell capacity is reasonable.
> refactor(ckb): Remove 1CKB from BTC time cell capacity

- .changeset/clean-snails-admire.md
- .changeset/sharp-wasps-punch.md
- .changeset/shy-tables-turn.md
- .changeset/three-hounds-listen.md
- packages/btc/CHANGELOG.md
- packages/btc/package.json
- packages/ckb/CHANGELOG.md
- packages/ckb/package.json
- packages/rgbpp/CHANGELOG.md
- packages/rgbpp/package.json
- packages/service/CHANGELOG.md
- packages/service/package.json
- [#261](https://github.com/ckb-cell/rgbpp-sdk/pull/261): Batch fetch CKB RGB++ live cells to construct BTC transaction ([@duanyytop](https://github.com/duanyytop))
- Batch fetch CKB RGB++ live cells to construct BTC transaction
- Remove useless fields for RGB++ lock args list
- Updated dependencies [[`9afc2a9`](https://github.com/ckb-cell/rgbpp-sdk/commit/9afc2a911e6a4ba8a200755b01159b5b149e4010), [`8f99429`](https://github.com/ckb-cell/rgbpp-sdk/commit/8f99429de45899e5169771e87e73603318a49ae8), [`475b3c3`](https://github.com/ckb-cell/rgbpp-sdk/commit/475b3c35ab1a25ba3aae28123f2820460101c889)]:
- @rgbpp-sdk/service@0.5.0
- @rgbpp-sdk/ckb@0.5.0
- [#258](https://github.com/ckb-cell/rgbpp-sdk/pull/258): Support for arbitrary BTC confirmation blocks to unlock btc time …
> Bump RGB++ SDK to v0.5.0

- .changeset/tiny-beds-protect.md
- packages/btc/README.md
- packages/btc/src/api/sendUtxos.ts
- packages/btc/src/error.ts
- packages/btc/tests/Transaction.test.ts
- Add a `context` prop in the TxBuildError to report more info; The `TxBuilderError.context.tx` (a TxBuilder object) should exist when the BTC Builder APIs fail. For example, you should be able to visit the context when calling the `sendBtc` API and it fails:
```ts
try {
await sendBtc(...);
} catch (e) {
if (e instanceof TxBuildError) {
console.log(e.context.tx); // TxBuilder
}
}
```
- Update the message of the MISSING_PUBKEY error
```
Missing a pubkey that pairs with the address, it is required for the P2TR UTXO included in the transaction: {address}
```
- Resolves #266 
- Improves error tracing for users #260
> feat(btc): report extra context in the TxBuildError

- packages/rgbpp/src/index.ts
- Expose `RgbppTransferAllTxGroup` and `TransactionGroupSummary` types in the rgbpp lib
> This change is minor, so a changeset is not required
> feat(rgbpp): expose more l1-transfer-all related types

- examples/rgbpp/README.md
- examples/rgbpp/xudt/btc-transfer-all/1-btc-transfer-all.ts
- This example demonstrates a batch transfer of RGBPP XUDT assets.
- It shows the process of transferring all assets from one account to another on the BTC network.
> feat(example): Add example for batch transfer of RGBPP XUDT assets

- .changeset/rotten-carrots-raise.md
- apps/service/src/rgbpp/rgbpp.service.ts
- apps/service/src/rgbpp/types.ts
- examples/rgbpp/xudt/btc-transfer-all/1-btc-transfer-all.ts
- packages/rgbpp/src/index.ts
- packages/rgbpp/src/rgbpp/utils/transaction.ts
-  Update response of sending RGB++ group transactions
-  Add `send_rgbpp_group_txs` RPC to SDK service
- Update `generate_rgbpp_transfer_all_txs` response
> refactor(rgbpp|service): Add `send_rgbpp_group_txs` RPC to SDK Service

- .changeset/odd-cheetahs-shake.md
- packages/service/README.md
- packages/service/src/service/service.ts
- packages/service/src/types/btc.ts
- packages/service/src/types/rgbpp.ts
- packages/service/tests/Service.test.ts
- Add support of the `/rgbpp/v1/address/{btc_address}/activity` API for querying RGBPP asset activities by an BTC address, adapting changes in [btc-assets-api#182](https://github.com/ckb-cell/btc-assets-api/pull/182) and [btc-assets-api#194](https://github.com/ckb-cell/btc-assets-api/pull/194)
- Fix the type of `BtcApiBlockchainInfo.bestblockhash` to `string`
- Update types in the service lib README
- https://github.com/ckb-cell/btc-assets-api/issues/214
> feat(service): support /rgbpp/v1/address/{btc_address}/activity

- .changeset/sweet-cheetahs-drop.md
- examples/rgbpp/README.md
- examples/rgbpp/xudt/compatible-xudt/1-ckb-leap-btc.ts
- examples/rgbpp/xudt/compatible-xudt/2-btc-transfer.ts
- examples/rgbpp/xudt/compatible-xudt/3-btc-leap-ckb.ts
- examples/rgbpp/xudt/compatible-xudt/assets-api.ts
- packages/ckb/src/constants/index.ts
- packages/ckb/src/rgbpp/btc-time.ts
- packages/ckb/src/utils/cell-dep.spec.ts
- packages/ckb/src/utils/cell-dep.ts
- packages/ckb/src/utils/ckb-tx.ts
- tests/rgbpp/xudt/compatible-xudt/1-ckb-leap-btc.ts
- tests/rgbpp/xudt/compatible-xudt/2-btc-transfer.ts
- tests/rgbpp/xudt/compatible-xudt/3-btc-leap-ckb.ts
- Add USDI to compatible xUDT list
- Fetch and cache compatible xUDT list from Vercel or GitHub server
- Use local static compatible xUDT list when the cache is empty
- Remove jsdelivr CDN because CDN cache time is too long, causing UTXO Airdrop cellDeps to become outdated
- Update UtxoAirdropBadge `cellDeps` test
> Add USDI to compatible xUDT list

- .changeset/tough-foxes-add.md
- examples/rgbpp/xudt/offline/1-prepare-launch.ts
- examples/rgbpp/xudt/offline/2-launch-rgbpp.ts
- examples/rgbpp/xudt/offline/3-distribute-rgbpp.ts
- examples/rgbpp/xudt/offline/4-btc-leap-ckb.ts
- examples/rgbpp/xudt/offline/5-unlock-btc-time-cell.ts
- examples/rgbpp/xudt/offline/6-ckb-leap-btc.ts
- packages/ckb/src/rgbpp/btc-time.ts
- packages/ckb/src/rgbpp/btc-transfer.ts
- packages/ckb/src/spore/spore.ts
- packages/ckb/src/utils/ckb-tx.ts
Extract the logic for supplementing transaction fees into separate methods to facilitate users handling the signing logic for the final CKB transaction on their own.
xUDT testing transactions on Testnet3 in offline mode:
1. Issuance preparation 
- CKB tx: https://testnet.explorer.nervos.org/transaction/0x24d5da586b046475959271f4a23458b9b3569babeccaf5857f1659791a856d43
2. Issuance:
- BTC tx: https://mempool.space/testnet/tx/65e0574dfdbed4809736f3ec5a73aa191f147873d083ddb9978aecb969dd1900
- CKB tx: https://testnet.explorer.nervos.org/transaction/0xc323ee59b725a5b067df10360fe4b675bd1079f90473a4bb19ce8650c51a9759
3. Distribution:
- BTC tx: https://mempool.space/testnet/tx/dfb3be075b831ce7605ab3f56b7dda39ba7438e015ded3332db1f54cfac161de
- CKB tx: …
> refactor(ckb): encapsulate transaction fee supplementation methods

- tests/rgbpp/shared/utils.ts
- Update the basic fee rate for integration-tests from `fastestFee + 1000` to `fastestFee * 1.1`
> test: use fastestFee * 1.1 as basic btc-fee for integration-tests

- .changeset/lazy-shrimps-roll.md
- examples/rgbpp/xudt/offline/compatible-xudt/1-ckb-leap-btc.ts
- examples/rgbpp/xudt/offline/compatible-xudt/2-btc-transfer.ts
- examples/rgbpp/xudt/offline/compatible-xudt/3-btc-leap-ckb.ts
- examples/rgbpp/xudt/offline/compatible-xudt/4-unlock-btc-time-cell.ts
- packages/ckb/src/rgbpp/btc-jump-ckb.ts
- packages/ckb/src/rgbpp/btc-time.ts
- packages/ckb/src/rgbpp/btc-transfer.ts
- packages/ckb/src/rgbpp/ckb-jump-btc.ts
- packages/ckb/src/utils/cell-dep.ts
- packages/ckb/src/utils/ckb-tx.ts
- packages/ckb/src/utils/rgbpp.ts
- packages/rgbpp/src/rgbpp/summary/asset-summarizer.ts
- packages/rgbpp/src/rgbpp/types/xudt.ts
- packages/rgbpp/src/rgbpp/xudt/btc-transfer-all.ts
This update introduces offline mode support for compatible xUDT type scripts by adding an optional `offline` parameter to related methods. That is, if a user chooses to stay completely offline during the transaction building process, the compatible xUDT type scripts used will be the local ones instead of fetching them from the network.
The `offline` behavior is determined by the `vendorCellDeps` parameter, so there's no need for an extra parameter. Given the current implementation of using `rgbpp-sdk` in offline mode, it's safe to deduce the user's intention simply by checking whether `vendorCellDeps` is provided.
Compatible xUDT testing transactions on Testnet3 in offline mode:
1. Jumping from CKB to BTC:
- CKB tx: https://testnet.explorer.nervos.org/transaction/0x8aa74b1e9c37f1d1672d0555 …
> feat: add offline mode support for compatible xUDT type scripts
