packages/ckb/src/utils/rgbpp.ts

- Add isRgbppLockCell and isBtcTimeLockCell methods for BTC package
@Flouse @ShookLyngs

feat(rgbpp-sdk/ckb): Add more ckb utils methods for BTC package

---

packages/ckb/src/utils/rgbpp.ts

- Update `isRgbppLockCell` and `isBtcTimeLockCell` methods
@ShookLyngs

feat(rgbpp-sdk/ckb): Update isRgbppLockCell and isBtcTimeLockCell methods

---

packages/ckb/src/constants/index.ts

- Update RGBPP lock and BTC time lock Testnet deployment
RGBPP lock: https://github.com/ckb-cell/rgbpp-deployment/blob/master/rgbpp/deploy_info.json
BTC time lock: https://github.com/ckb-cell/rgbpp-deployment/blob/master/btc-time-lock/deploy_info.json
@Flouse @ShookLyngs @Dawn-githup

feat(rgbpp-sdk/ckb): Update rgbpp lock testnet deployment

---

packages/btc/package.json
packages/btc/src/api/sendRgbppUtxos.ts
pnpm-lock.yaml

- Replace type `RawTranasction` with `CKBComponents.RawTransaction` (mentioned by @duanyytop)
- Remove unused line of code (mentioned in https://github.com/ckb-cell/rgbpp-sdk/issues/37 by @Flouse)

fix: RawTransaction to CKBComponents.RawTransaction

---

packages/btc/README.md

- Guide developers to get access token via email
- Explain the difference between origin and domain (with or without the protocol)

docs(rgbpp-sdk/btc): explain the difference between origin/domain

---

packages/ckb/package.json

- Add ckb package types to package.json

fix(rgbpp-sdk/ckb): Add ckb package types to package.json

---

apps/next/next.config.mjs
apps/next/package.json
apps/next/src/app/page.tsx
apps/vite/package.json
apps/vite/src/App.tsx
pnpm-lock.yaml

- Migrate apps to support the latest version of sdk

refactor: update apps with the latest packages

---

packages/service/src/service/service.ts

- Rename BtcAssetsApi API params based on changes in https://github.com/ckb-cell/btc-assets-api/pull/17

refactor(rgbpp-sdk/service): sync with btc-assets-api#17

---

packages/ckb/src/rgbpp/ckb-jump-btc.ts

- Update collect capacity for CKB jumping BTC

fix(rgbpp-sdk/ckb): Update collect capacity for CKB jumping BTC

---

packages/ckb/src/rgbpp/btc-jump-ckb.ts

- Update RGBPP lock out_index for jumping from BTC to CKB

refactor(rgbpp-sdk/ckb): Update out_index for jumping from BTC to CKB

---

packages/ckb/src/rgbpp/ckb-jump-btc.ts

- Update needs capacity for jumping from CKB to BTC to have enough capacity for change

fix(rgbpp-sdk/ckb): Update needCapacity for jumping from CKB to BTC

---

packages/ckb/src/collector/index.ts
packages/ckb/src/rgbpp/btc-jump-ckb.ts
packages/ckb/src/rgbpp/btc-transfer.ts
packages/ckb/src/rgbpp/ckb-jump-btc.ts

- Unlock all RGB++ assets(the same xudt type) of the same RGBPP lock script

feat(rgbpp-sdk/ckb): Unlock all rgbpp asset of the same rgbpp lock

---

packages/btc/src/api/sendRgbppUtxos.ts
packages/btc/tests/Transaction.test.ts

refactor(rgbpp-sdk/btc): mark RGBPP UTXOs as fixed in `sendRgbppUtxos`

---

packages/ckb/src/error/index.ts
packages/ckb/src/rgbpp/btc-jump-ckb.ts
packages/ckb/src/rgbpp/btc-transfer.ts
packages/ckb/src/rgbpp/ckb-jump-btc.ts
packages/ckb/src/utils/ckb-tx.spec.ts
packages/ckb/src/utils/ckb-tx.ts

- Check whether the type script is supported for RGB++ transactions
- Add `isTypeAssetSupported` function to check type scripts

feat(rgbpp-sdk/ckb): Check whether the type script is supported

---

examples/rgbpp/local/1-mint-xudt.ts
examples/rgbpp/local/2-ckb-jump-btc.ts
examples/rgbpp/local/3-btc-transfer.ts
examples/rgbpp/local/4-btc-jump-ckb.ts
examples/rgbpp/local/5-spend-btc-time-cell.ts
examples/rgbpp/queue/1-mint-xudt.ts
examples/rgbpp/queue/2-ckb-jump-btc.ts
examples/rgbpp/queue/3-btc-transfer.ts
examples/rgbpp/queue/4-btc-jump-ckb.ts
examples/rgbpp/queue/no-merge-outputs/3-btc-transfer.ts

- Update examples secp256k1 cell dep
- Update examples CKB addresses for Testnet and Mainnet

refactor(examples): Update examples secp256k1 cell dep and ckb address

---

examples/rgbpp/local/3-btc-transfer.ts
examples/rgbpp/local/4-btc-jump-ckb.ts
examples/rgbpp/local/5-spend-btc-time-cell.ts
examples/rgbpp/queue/3-btc-transfer.ts
examples/rgbpp/queue/4-btc-jump-ckb.ts
examples/rgbpp/queue/no-merge-outputs/3-btc-transfer.ts

- Update examples function param `isMainnet`

refactor(examples): Update examples function param isMainnet

---

packages/btc/src/api/sendRgbppUtxos.ts

- Resolves #75 (sugessted by @duanyytop)

refactor(rgbpp-sdk/btc): improve readability of the sendRgbppUtxos() API

---

package.json
packages/btc/package.json
packages/ckb/package.json
packages/service/package.json
pnpm-lock.yaml

- Update dependencies version for the repo (`turbo` is also updated, we can observe whether the #57 issue still appears in the future)

chore: update dependencies

---

packages/ckb/src/constants/index.ts

- Add RGB++ contracts Mainnet deployment

feat(rgbpp-sdk/ckb): Add mainnet deployment info

---

packages/ckb/README.md
packages/ckb/src/rgbpp/btc-jump-ckb.ts
packages/ckb/src/rgbpp/btc-time.ts
packages/ckb/src/rgbpp/btc-transfer.ts
packages/ckb/src/rgbpp/ckb-builder.ts
packages/ckb/src/rgbpp/ckb-jump-btc.ts
packages/ckb/src/types/rgbpp.ts

- Add CKB transaction fee rate
- Update CKB package readme
- Add `witnessLockPlaceholderSize` to CKB virtual tx methods

feat(rgbpp-sdk/ckb): Add ckb transaction fee rate

---

packages/btc/package.json
packages/btc/src/ckb/molecule.ts
packages/btc/src/utils.ts
packages/ckb/package.json
packages/service/package.json
packages/service/src/service/service.ts
packages/service/src/types/rgbpp.ts
packages/service/tests/Service.test.ts
pnpm-lock.yaml

- Upgrade lumos version to v0.22.2
- Replace lumos package with sub-packages

feat(rgbpp-sdk): Update lumos sub packages version

---

packages/service/src/service/base.ts

refactor(service): support parsing more service errors

---

packages/btc/src/api/sendBtc.ts

- Simplify the inner logic of the sendBtc() API with the createSendUtxosBuilder() API in the @rgbpp-sdk/btc

feat(btc): simplify inner logic of the sendBtc API

---

examples/rgbpp/spore/6-unlock-btc-time-cell.ts

- Update spore example isDataMustBeEmpty

fix(exmple): Update spore example isDataMustBeEmpty

---

.changeset/beige-apricots-swim.md
.changeset/cool-terms-raise.md
.changeset/dirty-walls-beg.md
.changeset/fair-impalas-crash.md
.changeset/few-paws-notice.md
.changeset/fifty-gifts-wonder.md
.changeset/good-foxes-whisper.md
.changeset/gorgeous-dots-rest.md
.changeset/gorgeous-starfishes-prove.md
.changeset/great-coins-smile.md
.changeset/hip-horses-tease.md
.changeset/lovely-rings-do.md
.changeset/metal-carpets-joke.md
.changeset/new-phones-lick.md
.changeset/nice-grapes-rule.md
.changeset/pretty-foxes-own.md
.changeset/silly-roses-pay.md
.changeset/silver-readers-melt.md
.changeset/smart-items-lie.md
.changeset/soft-melons-hug.md
.changeset/twelve-forks-float.md
package.json
packages/btc/CHANGELOG.md
packages/btc/README.md
packages/ckb/CHANGELOG.md
packages/ckb/README.md
packages/service/CHANGELOG.md
packages/service/README.md

- Clean changesets, we don't need them in our first changelog update
- Update README docs, recommend to install the latest tag, e.g. `@rgbpp-sdk/btc@snap` -> `@rgbpp-sdk/btc`

bump: 0.1.0

---

.changeset/beige-apricots-swim.md
.changeset/cool-terms-raise.md
.changeset/dirty-walls-beg.md
.changeset/fair-impalas-crash.md
.changeset/few-paws-notice.md
.changeset/fifty-gifts-wonder.md
.changeset/good-foxes-whisper.md
.changeset/gorgeous-dots-rest.md
.changeset/gorgeous-starfishes-prove.md
.changeset/great-coins-smile.md
.changeset/hip-horses-tease.md
.changeset/lovely-rings-do.md
.changeset/metal-carpets-joke.md
.changeset/new-phones-lick.md
.changeset/nice-grapes-rule.md
.changeset/pretty-foxes-own.md
.changeset/silly-roses-pay.md
.changeset/silver-readers-melt.md
.changeset/smart-items-lie.md
.changeset/soft-melons-hug.md
.changeset/twelve-forks-float.md
package.json
packages/btc/CHANGELOG.md
packages/btc/README.md
packages/ckb/CHANGELOG.md
packages/ckb/README.md
packages/service/CHANGELOG.md
packages/service/README.md

Bump version to v0.1.0

---

apps/vite/package.json
pnpm-lock.yaml

- Upgrade vite version for apps to fix security alert

fix(apps/vite): Upgrade vite version

---

.changeset/slimy-eggs-mix.md
packages/ckb/src/spore/leap.ts
packages/ckb/src/spore/spore.ts
packages/ckb/src/utils/ckb-tx.ts
packages/ckb/src/utils/rgbpp.ts
packages/ckb/src/utils/spore.spec.ts
packages/ckb/src/utils/spore.ts

- Check if the type is the supported spore type script for spore transfer and leap

refactor(rgbpp-sdk/ckb): Check spore type script for spore transfer and leap

---

.changeset/sweet-jeans-check.md
packages/ckb/src/utils/ckb-tx.ts

- Update ckb cell fields size to make code more readable

refactor(rgbpp-sdk/ckb): Update ckb cell fields size

---

packages/btc/src/transaction/build.ts

- Add notes/comments to better explain the inner logic of the `TxBuilder.payFee()` related functions
> The change doesn't include actual logic refactors, therefore no changeset was added
- Resolves #140

refactor(btc): add notes to TxBuilder.payFee() related functions

---

.github/workflows/snapshot.yml
package.json

- Simplify snapshot/release workflows, merging steps
- Stop triggering the snapshot.yaml workflow when main branch updates

chore(ci): simplify snapshot/release workflow and trigger branches

---

.changeset/great-goats-repair.md
examples/rgbpp/shared/utils.ts
packages/ckb/src/rgbpp/launch.ts
packages/ckb/src/spore/cluster.ts
packages/ckb/src/spore/spore.ts
packages/ckb/src/types/rgbpp.ts
packages/ckb/src/types/spore.ts
pnpm-lock.yaml

- Return `needPaymasterCell` for cluster and spore creation virtual transaction 
- Return `needPaymasterCell` for RGB++ xUDT launching

feat(rgbpp-sdk/ckb): Return needPaymasterCell for spore and xudt

---

examples/rgbpp/README.md

- Add example commands comment and FAQ link
- More FAQs will be added to the [wiki](https://github.com/ckb-cell/rgbpp-sdk/wiki/RGBPP--FAQ)

docs(examples): Add example commands comment and FAQ link

---

examples/rgbpp/env.ts
examples/xudt-on-ckb/env.ts

- Replace example CKB short address with full address

refactor(examples): Replace example ckb short address with full address

---

.github/workflows/integration-test.yaml
tests/rgbpp/package.json
tests/rgbpp/shared/prepare-utxo.ts
tests/rgbpp/shared/utils.ts
tests/rgbpp/spore/4-transfer-spore.ts
tests/rgbpp/spore/5-leap-spore-to-ckb.ts
tests/rgbpp/spore/launch/0-cluster-info.ts
tests/rgbpp/spore/launch/1-prepare-cluster.ts
tests/rgbpp/spore/launch/2-create-cluster.ts
tests/rgbpp/spore/launch/3-create-spores.ts
tests/rgbpp/xudt/1-ckb-leap-btc.ts
tests/rgbpp/xudt/2-btc-transfer.ts
tests/rgbpp/xudt/3-btc-leap-ckb.ts
tests/rgbpp/xudt/xudt-on-ckb/1-issue-xudt.ts

- Created spore integration tests.
- Refactored workflow to enable parallel testing, improving test efficiency.
- Renamed log files for better clarity and readability.

test: Create spore integration tests

---

tests/rgbpp/package.json
tests/rgbpp/xudt/xudt-on-ckb/2-transfer-xudt.ts

- Write tests to make sure transfer-xudt works as expected. These tests will verify if transfers happen correctly.

test: Add transfer-xudt integration tests

---

.github/workflows/docker.yml

For now: https://github.com/ckb-cell/rgbpp-sdk/pkgs/container/rgbpp-sdk

ci: change service docker image name

---

packages/ckb/src/collector/collector.spec.ts
packages/ckb/src/collector/index.ts

- Support batch requests for fetching live cells from the CKB node
- Add tests for the collector

feat(rgbpp-sdk/ckb): Support batch requests for live cells

---

apps/service/src/rgbpp/rgbpp.service.ts
apps/service/src/rgbpp/types.ts

- Add `send_btc_transaction rpc` to RGB++ SDK Service

feat(sdk-service): Add `send_btc_transaction rpc` to SDK service

---

.github/workflows/integration-test.yaml
tests/rgbpp/env.ts
tests/rgbpp/shared/prepare-utxo.ts
tests/rgbpp/shared/utils.ts
tests/rgbpp/spore/4-transfer-spore.ts
tests/rgbpp/spore/5-leap-spore-to-ckb.ts
tests/rgbpp/spore/launch/2-create-cluster.ts
tests/rgbpp/spore/launch/3-create-spores.ts
tests/rgbpp/xudt/2-btc-transfer.ts
tests/rgbpp/xudt/3-btc-leap-ckb.ts
tests/rgbpp/xudt/xudt-on-ckb/1-issue-xudt.ts

- Switched from Signet to Testnet3 for testing due to insufficient Signet test resources
- Added pull_request trigger for tests
- Updated btcConfirmationBlocks in btc-leap-ckb to 20 instead of using the default value of 6"

test: resolve integration test failures due to insufficient test tokens

---

.github/workflows/integration-test.yaml
.github/workflows/release.yml
.github/workflows/snapshot.yml
.github/workflows/test.yaml
package.json
pnpm-lock.yaml

- Version requirement for pnpm: v8 -> v9
- Version Requirement for node: v18 -> v21

chore: tune up node/pnpm version requirements

---

examples/rgbpp/spore/launch/3-create-spores.ts

- Check spore creation transaction size to make sure the CKB transaction can be committed to the blockchain

feat(spore-example): Check spore creation tx size

---

.github/workflows/integration-test.yaml
tests/rgbpp/env.ts
tests/rgbpp/shared/prepare-utxo.ts
tests/rgbpp/spore/4-transfer-spore.ts
tests/rgbpp/spore/5-leap-spore-to-ckb.ts
tests/rgbpp/spore/launch/2-create-cluster.ts
tests/rgbpp/spore/launch/3-create-spores.ts
tests/rgbpp/xudt/2-btc-transfer.ts
tests/rgbpp/xudt/3-btc-leap-ckb.ts
tests/rgbpp/xudt/btc-transfer-all/1-btc-transfer-all.ts

- Switching from Testnet3 to Signet for testing.

test: Switching from Testnet3 to Signet for testing
